prenom = input("Entrez votre prénom : ")
nom = input("Entrez votre nom : ")
age = input("Entrez votre âge : ")
annee_naissance = 2024 - int(age)
print("Bonjour,", prenom, nom)
print("Vous avez", age, "ans.")
print("Vous êtes né(e) en", annee_naissance)